title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jahan002disney.github.io/justTheDocsTrial

aux_links:
  Template Repository: https://github.com/jahan002disney/justTheDocsTrial
